#!/usr/bin/env bash
# =============================================================================
# setup.sh — Install devco-agent-skills into user-level Claude Code config
# =============================================================================
#
# What this does:
#   1. Writes plugin CLAUDE.md content into ~/.claude/CLAUDE.md
#      → Auto-loaded by Claude in EVERY session across ALL projects
#   2. Optionally copies rules/ into .claude/rules/ of the current project
#      → Auto-loaded by Claude for this project only
#
# Usage:
#   bash scripts/setup.sh              # Global setup only
#   bash scripts/setup.sh --project    # Global + current project rules
#   bash scripts/setup.sh --update     # Refresh after plugin update
#
# Safe to re-run: idempotent, uses start/end markers.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

USER_CLAUDE_DIR="$HOME/.claude"
USER_CLAUDE_MD="$USER_CLAUDE_DIR/CLAUDE.md"

MARKER_START="<!-- devco-agent-skills:start -->"
MARKER_END="<!-- devco-agent-skills:end -->"

WITH_PROJECT=false
for arg in "$@"; do
  case "$arg" in
    --project|-p) WITH_PROJECT=true ;;
    --update|-u)  : ;; # same as default — idempotent
  esac
done

# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

ok()   { echo "  ✅  $*"; }
info() { echo "  →   $*"; }
warn() { echo "  ⚠️   $*"; }
h()    { echo ""; echo "── $* ──────────────────────────────────────────"; }

# ---------------------------------------------------------------------------
# 1. Global: write to ~/.claude/CLAUDE.md
# ---------------------------------------------------------------------------

h "Global setup: ~/.claude/CLAUDE.md"

mkdir -p "$USER_CLAUDE_DIR"
touch "$USER_CLAUDE_MD"

# Remove existing block (idempotent update)
if grep -q "$MARKER_START" "$USER_CLAUDE_MD" 2>/dev/null; then
  TMPFILE="$(mktemp)"
  awk "
    /$MARKER_START/ { skip=1 }
    !skip           { print }
    /$MARKER_END/   { skip=0 }
  " "$USER_CLAUDE_MD" > "$TMPFILE"
  mv "$TMPFILE" "$USER_CLAUDE_MD"
  info "Removed previous devco-agent-skills block"
fi

# Append fresh block
{
  printf '\n'
  echo "$MARKER_START"
  echo "<!-- Generated by devco-agent-skills/scripts/setup.sh $(date -u '+%Y-%m-%dT%H:%MZ') -->"
  echo "<!-- Re-run after plugin updates: bash ~/.claude/plugins/cache/devco-agent-skills/scripts/setup.sh --update -->"
  printf '\n'
  cat "$PLUGIN_DIR/CLAUDE.md"
  printf '\n'
  echo "$MARKER_END"
  printf '\n'
} >> "$USER_CLAUDE_MD"

BLOCK_LINES="$(awk "/$MARKER_START/{found=1} found{c++} /$MARKER_END/{found=0} END{print c}" "$USER_CLAUDE_MD")"
ok "Plugin instructions installed ($BLOCK_LINES lines) → $USER_CLAUDE_MD"
info "These rules auto-load in EVERY Claude Code session on this machine."

# ---------------------------------------------------------------------------
# 2. Per-project: copy rules/ into .claude/rules/ of current project
# ---------------------------------------------------------------------------

if [ "$WITH_PROJECT" = "true" ]; then
  h "Project setup: .claude/rules/"

  # Detect project root
  PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

  # Don't install into the plugin repo itself
  if [ "$PROJECT_ROOT" = "$PLUGIN_DIR" ]; then
    warn "Current directory is the plugin repo — skipping project rules install."
  else
    RULES_SRC="$PLUGIN_DIR/rules"
    RULES_DST="$PROJECT_ROOT/.claude/rules"

    mkdir -p "$RULES_DST"

    # Copy all rule files, preserving subdirectory structure
    find "$RULES_SRC" -name "*.md" | while IFS= read -r src_file; do
      rel="${src_file#$RULES_SRC/}"
      dst_file="$RULES_DST/$rel"
      mkdir -p "$(dirname "$dst_file")"
      cp "$src_file" "$dst_file"
    done

    RULE_COUNT="$(find "$RULES_DST" -name "*.md" | wc -l | tr -d ' ')"
    ok "$RULE_COUNT rule files installed → $RULES_DST"
    info "Rules auto-load for this project only."
    info "Add .claude/rules/ to version control to share with your team."
  fi
fi

# ---------------------------------------------------------------------------
# 3. Print next steps
# ---------------------------------------------------------------------------

h "Done"
echo ""
echo "  Installed components:"
echo "    ~/.claude/CLAUDE.md   — global rules, loaded every session everywhere"
if [ "$WITH_PROJECT" = "true" ]; then
  echo "    .claude/rules/        — project rules, loaded for this project"
fi
echo ""
echo "  Next time you work on a new project, run:"
echo "    /setup --project"
echo "  or:"
echo "    bash ~/.claude/plugins/cache/devco-agent-skills/scripts/setup.sh --project"
echo ""
echo "  To refresh after a plugin update:"
echo "    bash ~/.claude/plugins/cache/devco-agent-skills/scripts/setup.sh --update"
echo ""
