#!/usr/bin/env bash
# =============================================================================
# setup.sh — Install devco-agent-skills into a project (or globally)
# =============================================================================
#
# Default (project scope):
#   1. Injects plugin CLAUDE.md into PROJECT_ROOT/CLAUDE.md  (markers, idempotent)
#   2. Copies WORKING_WORKFLOW.md  →  PROJECT_ROOT/WORKING_WORKFLOW.md
#   3. Copies rules/               →  PROJECT_ROOT/.claude/rules/
#
# Optional --global:
#   4. Injects plugin CLAUDE.md into ~/.claude/CLAUDE.md
#      → auto-loads in every session on this machine
#
# Usage:
#   bash scripts/setup.sh              # Project setup (CLAUDE.md + workflow + rules)
#   bash scripts/setup.sh --global     # Also write to ~/.claude/CLAUDE.md
#   bash scripts/setup.sh --update     # Refresh (idempotent re-run)
#
# Safe to re-run: idempotent via start/end markers.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

MARKER_START="<!-- devco-agent-skills:start -->"
MARKER_END="<!-- devco-agent-skills:end -->"

WITH_GLOBAL=false
for arg in "$@"; do
  case "$arg" in
    --global|-g) WITH_GLOBAL=true ;;
    --update|-u) : ;;  # idempotent re-run — same as default
  esac
done

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

ok()   { echo "  ✅  $*"; }
info() { echo "  →   $*"; }
warn() { echo "  ⚠️   $*"; }
h()    { echo ""; echo "── $* ──────────────────────────────────────────"; }

# Inject plugin content into a target file using markers (idempotent)
inject_plugin_content() {
  local target="$1"
  local content_file="$2"

  touch "$target"

  # Remove existing block
  if grep -q "$MARKER_START" "$target" 2>/dev/null; then
    local tmpfile
    tmpfile="$(mktemp)"
    awk "
      /$MARKER_START/ { skip=1 }
      !skip           { print }
      /$MARKER_END/   { skip=0 }
    " "$target" > "$tmpfile"
    mv "$tmpfile" "$target"
    info "Removed previous devco-agent-skills block from $(basename "$target")"
  fi

  # Append fresh block
  {
    printf '\n'
    echo "$MARKER_START"
    echo "<!-- Generated by devco-agent-skills/scripts/setup.sh $(date -u '+%Y-%m-%dT%H:%MZ') -->"
    echo "<!-- Re-run to refresh: bash scripts/setup.sh --update -->"
    printf '\n'
    cat "$content_file"
    printf '\n'
    echo "$MARKER_END"
    printf '\n'
  } >> "$target"

  local block_lines
  block_lines="$(awk "/$MARKER_START/{found=1} found{c++} /$MARKER_END/{found=0} END{print c}" "$target")"
  echo "$block_lines"
}

# ---------------------------------------------------------------------------
# Detect project root
# ---------------------------------------------------------------------------

PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

# Guard: skip if running from inside the plugin repo itself
if [ "$PROJECT_ROOT" = "$PLUGIN_DIR" ]; then
  warn "Running from plugin repo — project-scope install skipped."
  warn "Run from a target project directory instead."
  WITH_GLOBAL=true  # Fall through to global only
  SKIP_PROJECT=true
else
  SKIP_PROJECT=false
fi

# ---------------------------------------------------------------------------
# 1. Project scope — CLAUDE.md
# ---------------------------------------------------------------------------

if [ "$SKIP_PROJECT" = "false" ]; then
  h "Project scope: $PROJECT_ROOT"

  # 1a. CLAUDE.md
  PROJECT_CLAUDE_MD="$PROJECT_ROOT/CLAUDE.md"
  if [ -f "$PROJECT_CLAUDE_MD" ]; then
    info "Existing CLAUDE.md found — injecting plugin rules with markers"
    lines="$(inject_plugin_content "$PROJECT_CLAUDE_MD" "$PLUGIN_DIR/CLAUDE.md")"
    ok "Plugin rules injected into CLAUDE.md ($lines lines) — auto-loads for this project"
  else
    cp "$PLUGIN_DIR/CLAUDE.md" "$PROJECT_CLAUDE_MD"
    ok "CLAUDE.md created at project root — auto-loads for this project"
  fi

  # 1b. WORKING_WORKFLOW.md
  WORKFLOW_SRC="$PLUGIN_DIR/WORKING_WORKFLOW.md"
  WORKFLOW_DST="$PROJECT_ROOT/WORKING_WORKFLOW.md"
  if [ -f "$WORKFLOW_SRC" ]; then
    cp "$WORKFLOW_SRC" "$WORKFLOW_DST"
    ok "WORKING_WORKFLOW.md copied → $WORKFLOW_DST"
  else
    warn "WORKING_WORKFLOW.md not found in plugin dir — skipped"
  fi

  # 1c. rules/ → .claude/rules/
  RULES_SRC="$PLUGIN_DIR/rules"
  RULES_DST="$PROJECT_ROOT/.claude/rules"

  if [ -d "$RULES_SRC" ]; then
    mkdir -p "$RULES_DST"
    find "$RULES_SRC" -name "*.md" | while IFS= read -r src_file; do
      rel="${src_file#$RULES_SRC/}"
      dst_file="$RULES_DST/$rel"
      mkdir -p "$(dirname "$dst_file")"
      cp "$src_file" "$dst_file"
    done
    rule_count="$(find "$RULES_DST" -name "*.md" | wc -l | tr -d ' ')"
    ok "$rule_count rule files installed → $RULES_DST"
    info "Commit .claude/ to version control to share rules with your team."
  fi
fi

# ---------------------------------------------------------------------------
# 2. Global scope — ~/.claude/CLAUDE.md  (opt-in with --global)
# ---------------------------------------------------------------------------

if [ "$WITH_GLOBAL" = "true" ] && [ "$SKIP_PROJECT" = "false" ]; then
  h "Global scope: ~/.claude/CLAUDE.md"
  USER_CLAUDE_DIR="$HOME/.claude"
  USER_CLAUDE_MD="$USER_CLAUDE_DIR/CLAUDE.md"
  mkdir -p "$USER_CLAUDE_DIR"
  lines="$(inject_plugin_content "$USER_CLAUDE_MD" "$PLUGIN_DIR/CLAUDE.md")"
  ok "Plugin rules installed globally ($lines lines) → $USER_CLAUDE_MD"
  info "These rules auto-load in EVERY Claude Code session on this machine."
elif [ "$SKIP_PROJECT" = "true" ]; then
  # Running from plugin repo — global only
  h "Global scope: ~/.claude/CLAUDE.md"
  USER_CLAUDE_DIR="$HOME/.claude"
  USER_CLAUDE_MD="$USER_CLAUDE_DIR/CLAUDE.md"
  mkdir -p "$USER_CLAUDE_DIR"
  lines="$(inject_plugin_content "$USER_CLAUDE_MD" "$PLUGIN_DIR/CLAUDE.md")"
  ok "Plugin rules installed globally ($lines lines) → $USER_CLAUDE_MD"
fi

# ---------------------------------------------------------------------------
# 3. Summary
# ---------------------------------------------------------------------------

h "Done"
echo ""
echo "  Installed at project scope:"
echo "    CLAUDE.md               — loaded by Claude for this project"
echo "    WORKING_WORKFLOW.md     — 7-phase workflow reference"
echo "    .claude/rules/          — coding rules for this project"
if [ "$WITH_GLOBAL" = "true" ]; then
  echo ""
  echo "  Also installed globally:"
  echo "    ~/.claude/CLAUDE.md   — loaded in every session on this machine"
fi
echo ""
echo "  Add to version control to share with your team:"
echo "    git add CLAUDE.md WORKING_WORKFLOW.md .claude/rules/"
echo "    git commit -m 'chore: add Claude Code project context'"
echo ""
echo "  To refresh after a plugin update:"
echo "    bash scripts/setup.sh --update"
echo ""
