#!/usr/bin/env bash
# =============================================================================
# setup.sh — Install devco-agent-skills into a project (or globally)
# =============================================================================
#
# Default (project scope) — everything under PROJECT_ROOT/.claude/:
#   1. Injects plugin CLAUDE.md    →  PROJECT_ROOT/.claude/CLAUDE.md   (markers, idempotent)
#   2. Copies rules/               →  PROJECT_ROOT/.claude/rules/
#   3. Initializes memory          →  PROJECT_ROOT/.claude/memory/
#
# Optional --global:
#   4. Injects plugin CLAUDE.md into ~/.claude/CLAUDE.md
#      → auto-loads in every session on this machine
#
# Usage:
#   bash scripts/setup.sh              # Project setup (.claude/CLAUDE.md + workflow + rules)
#   bash scripts/setup.sh --global     # Also write to ~/.claude/CLAUDE.md
#   bash scripts/setup.sh --update     # Refresh (idempotent re-run)
#
# Safe to re-run: idempotent via start/end markers.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

MARKER_START="<!-- devco-agent-skills:start -->"
MARKER_END="<!-- devco-agent-skills:end -->"

WITH_GLOBAL=false
for arg in "$@"; do
  case "$arg" in
    --global|-g) WITH_GLOBAL=true ;;
    --update|-u) : ;;  # idempotent re-run — same as default
  esac
done

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

ok()   { echo "  ✅  $*"; }
info() { echo "  →   $*"; }
warn() { echo "  ⚠️   $*"; }
h()    { echo ""; echo "── $* ──────────────────────────────────────────"; }

# Inject plugin content into a target file using markers (idempotent)
inject_plugin_content() {
  local target="$1"
  local content_file="$2"

  touch "$target"

  # Remove existing block
  if grep -q "$MARKER_START" "$target" 2>/dev/null; then
    local tmpfile
    tmpfile="$(mktemp)"
    awk "
      /$MARKER_START/ { skip=1 }
      !skip           { print }
      /$MARKER_END/   { skip=0 }
    " "$target" > "$tmpfile"
    mv "$tmpfile" "$target"
    info "Removed previous devco-agent-skills block from $(basename "$target")"
  fi

  # Append fresh block
  {
    printf '\n'
    echo "$MARKER_START"
    echo "<!-- Generated by devco-agent-skills/scripts/setup.sh $(date -u '+%Y-%m-%dT%H:%MZ') -->"
    echo "<!-- Re-run to refresh: bash scripts/setup.sh --update -->"
    printf '\n'
    cat "$content_file"
    printf '\n'
    echo "$MARKER_END"
    printf '\n'
  } >> "$target"

  local block_lines
  block_lines="$(awk "/$MARKER_START/{found=1} found{c++} /$MARKER_END/{found=0} END{print c}" "$target")"
  echo "$block_lines"
}

# ---------------------------------------------------------------------------
# Detect project root
# ---------------------------------------------------------------------------

PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

# Guard: skip if running from inside the plugin repo itself
if [ "$PROJECT_ROOT" = "$PLUGIN_DIR" ]; then
  warn "Running from plugin repo — project-scope install skipped."
  warn "Run from a target project directory instead."
  WITH_GLOBAL=true  # Fall through to global only
  SKIP_PROJECT=true
else
  SKIP_PROJECT=false
fi

# ---------------------------------------------------------------------------
# 1. Project scope — CLAUDE.md
# ---------------------------------------------------------------------------

if [ "$SKIP_PROJECT" = "false" ]; then
  h "Project scope: $PROJECT_ROOT"

  CLAUDE_DIR="$PROJECT_ROOT/.claude"
  mkdir -p "$CLAUDE_DIR"

  # 1a. .claude/CLAUDE.md
  PROJECT_CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"
  if [ -f "$PROJECT_CLAUDE_MD" ]; then
    info "Existing .claude/CLAUDE.md found — injecting plugin rules with markers"
    lines="$(inject_plugin_content "$PROJECT_CLAUDE_MD" "$PLUGIN_DIR/CLAUDE.md")"
    ok "Plugin rules injected into .claude/CLAUDE.md ($lines lines) — auto-loads for this project"
  else
    cp "$PLUGIN_DIR/CLAUDE.md" "$PROJECT_CLAUDE_MD"
    ok ".claude/CLAUDE.md created — auto-loads for this project"
  fi

  # 1b. .claude/rules/
  RULES_SRC="$PLUGIN_DIR/rules"
  RULES_DST="$CLAUDE_DIR/rules"

  if [ -d "$RULES_SRC" ]; then
    mkdir -p "$RULES_DST"
    find "$RULES_SRC" -name "*.md" | while IFS= read -r src_file; do
      rel="${src_file#$RULES_SRC/}"
      dst_file="$RULES_DST/$rel"
      mkdir -p "$(dirname "$dst_file")"
      cp "$src_file" "$dst_file"
    done
    rule_count="$(find "$RULES_DST" -name "*.md" | wc -l | tr -d ' ')"
    ok "$rule_count rule files installed → $RULES_DST"
    info "Commit .claude/ to version control to share with your team."
  fi

  # 1c. Initialize memory directory
  if [ -f "$PLUGIN_DIR/scripts/memory/init.sh" ]; then
    bash "$PLUGIN_DIR/scripts/memory/init.sh" "$PROJECT_ROOT"
    ok "Memory directory initialized → $CLAUDE_DIR/memory/"
  fi

  # 1d. Team config → .claude/settings.json
  # Writes extraKnownMarketplaces + enabledPlugins so teammates are auto-prompted
  # to install the plugin on first `claude` run after git clone.
  # Hooks are NOT written here — they are handled by hooks/hooks.json via the
  # plugin system using ${CLAUDE_PLUGIN_ROOT}.
  SETTINGS_FILE="$CLAUDE_DIR/settings.json"
  SETTINGS_MARKER="devco-agent-skills"

  if [ ! -f "$SETTINGS_FILE" ] || ! grep -q "$SETTINGS_MARKER" "$SETTINGS_FILE" 2>/dev/null; then
    cat > "$SETTINGS_FILE" <<'SETTINGSJSON'
{
  "_comment": "devco-agent-skills — auto-generated by /setup. Hooks are registered via plugin system (hooks/hooks.json).",
  "extraKnownMarketplaces": {
    "devco-agent-skills": {
      "source": {
        "source": "github",
        "repo": "taipt1504/agent-skills"
      }
    }
  },
  "enabledPlugins": {
    "devco-agent-skills@devco-agent-skills": true
  }
}
SETTINGSJSON
    ok "Team config written → $SETTINGS_FILE"
    info "Teammates will be auto-prompted to install the plugin on git clone + claude."
  else
    info "Team config already present in $SETTINGS_FILE — skipped."
  fi
fi

# ---------------------------------------------------------------------------
# 2. Global scope — ~/.claude/CLAUDE.md  (opt-in with --global)
# ---------------------------------------------------------------------------

if [ "$WITH_GLOBAL" = "true" ] && [ "$SKIP_PROJECT" = "false" ]; then
  h "Global scope: ~/.claude/CLAUDE.md"
  USER_CLAUDE_DIR="$HOME/.claude"
  USER_CLAUDE_MD="$USER_CLAUDE_DIR/CLAUDE.md"
  mkdir -p "$USER_CLAUDE_DIR"
  lines="$(inject_plugin_content "$USER_CLAUDE_MD" "$PLUGIN_DIR/CLAUDE.md")"
  ok "Plugin rules installed globally ($lines lines) → $USER_CLAUDE_MD"
  info "These rules auto-load in EVERY Claude Code session on this machine."
elif [ "$SKIP_PROJECT" = "true" ]; then
  # Running from plugin repo — global only
  h "Global scope: ~/.claude/CLAUDE.md"
  USER_CLAUDE_DIR="$HOME/.claude"
  USER_CLAUDE_MD="$USER_CLAUDE_DIR/CLAUDE.md"
  mkdir -p "$USER_CLAUDE_DIR"
  lines="$(inject_plugin_content "$USER_CLAUDE_MD" "$PLUGIN_DIR/CLAUDE.md")"
  ok "Plugin rules installed globally ($lines lines) → $USER_CLAUDE_MD"
fi

# ---------------------------------------------------------------------------
# 3. Summary
# ---------------------------------------------------------------------------

h "Done (v3.0)"
echo ""
echo "  Installed at project scope (all under .claude/):"
echo "    .claude/CLAUDE.md           — project conventions (~400 tokens)"
echo "    .claude/rules/              — 9 coding rules (flat)"
echo "    .claude/memory/             — 3-tier session & knowledge storage"
echo "    .claude/settings.json       — team auto-install config"
echo ""
echo "  Workflow enforcement via bootstrap skill (hook-bootstrapped, not CLAUDE.md)."
echo "  Hooks registered via plugin system (hooks/hooks.json)."
if [ "$WITH_GLOBAL" = "true" ]; then
  echo ""
  echo "  Also installed globally:"
  echo "    ~/.claude/CLAUDE.md       — loaded in every session on this machine"
fi
echo ""
echo "  Share with your team:"
echo "    git add .claude/"
echo "    git commit -m 'chore: add Claude Code project context'"
echo ""
echo "  Refresh after plugin update:"
echo "    bash scripts/setup.sh --update"
echo ""
