#!/usr/bin/env bash
# docs-index.sh — auto-regenerate docs/{plans,specs}/INDEX.md when artifacts change
#
# Fires: PostToolUse on Write/Edit/MultiEdit when path matches docs/plans/** or docs/specs/**
# Effort: ~50ms for index regen, async.
set -euo pipefail

source "$(dirname "$0")/run-with-flags.sh" "docs-index" || exit 0

WORKSPACE="${CLAUDE_PROJECT_DIR:-$(/usr/bin/git rev-parse --show-toplevel 2>/dev/null || echo "$PWD")}"

regen_index() {
  local dir="$1"        # docs/plans or docs/specs
  local label="$2"      # "Plan" or "Spec"

  [ -d "$WORKSPACE/$dir" ] || return 0

  local index_file="$WORKSPACE/$dir/INDEX.md"
  local tmp="$index_file.tmp"

  {
    echo "# ${label}s — Index"
    echo ""
    echo "_Auto-generated by docs-index.sh. Do not edit manually — regenerate via /dc-status._"
    echo ""
    echo "| Feature | Shape | Status | Lane | Created |"
    echo "|---|---|---|---|---|"

    # Single-file ${label}s at top level
    while IFS= read -r f; do
      [ -f "$f" ] || continue
      [ "$(basename "$f")" = "INDEX.md" ] && continue
      local feature status lane created
      feature="$(basename "$f" .md)"
      status=$(/usr/bin/grep -m1 "^status:" "$f" 2>/dev/null | /usr/bin/awk '{print $2}' || echo "?")
      lane=$(/usr/bin/grep -m1 "^lane:" "$f" 2>/dev/null | /usr/bin/awk '{print $2}' || echo "?")
      created=$(/usr/bin/grep -m1 "^created:" "$f" 2>/dev/null | /usr/bin/awk '{print $2}' || echo "?")
      echo "| [${feature}](${feature}.md) | single | ${status} | ${lane} | ${created} |"
    done < <(/usr/bin/find "$WORKSPACE/$dir" -maxdepth 1 -name "*.md" -type f 2>/dev/null | /usr/bin/sort)

    # Split-shape ${label}s (directories with index.md)
    while IFS= read -r d; do
      local idx="$d/index.md"
      [ -f "$idx" ] || continue
      local feature status lane created slice_count
      feature="$(basename "$d")"
      status=$(/usr/bin/grep -m1 "^status:" "$idx" 2>/dev/null | /usr/bin/awk '{print $2}' || echo "?")
      lane=$(/usr/bin/grep -m1 "^lane:" "$idx" 2>/dev/null | /usr/bin/awk '{print $2}' || echo "?")
      created=$(/usr/bin/grep -m1 "^created:" "$idx" 2>/dev/null | /usr/bin/awk '{print $2}' || echo "?")
      slice_count=$(/usr/bin/grep -m1 "^slice_count:" "$idx" 2>/dev/null | /usr/bin/awk '{print $2}' || echo "?")
      echo "| [${feature}](${feature}/index.md) | split (${slice_count}) | ${status} | ${lane} | ${created} |"
    done < <(/usr/bin/find "$WORKSPACE/$dir" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | /usr/bin/sort)
  } > "$tmp"

  if [ -f "$index_file" ] && /usr/bin/cmp -s "$tmp" "$index_file"; then
    /bin/rm "$tmp"
  else
    /bin/mv "$tmp" "$index_file"
    echo "[docs-index] regenerated $dir/INDEX.md" >&2
  fi
}

regen_index "docs/plans" "Plan"
regen_index "docs/specs" "Spec"
regen_index "docs/adr" "ADR"

exit 0
